
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test.stephenzoio.com
  resources:
  - as
  verbs:
  - Create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.stephenzoio.com
  resources:
  - as/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - test.stephenzoio.com
  resources:
  - bs
  verbs:
  - Create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.stephenzoio.com
  resources:
  - bs/status
  verbs:
  - get
  - patch
  - update
