version: '3'
services:
  docker-in-docker:
    image: operatify-dev-container:0.1.0
    network_mode: "host"
    working_dir: /go/src/github.com/operatify/operatify
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/go/src/github.com/operatify/operatify

      # This lets you avoid setting up Git again in th container
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro # does not work on Windows! Will need to generate in container :(
      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity
